//
//  Model.swift
//  Quizz
//
//  Created by Mateus Filho on 31/05/19.
//  Copyright © 2019 Mateus Filho. All rights reserved.
//

import Foundation
import UIKit


class Singleton {
    static let shared = Singleton()
    private init () {
        
        
    }
    var acertos = 0
    var resultadosFinal :[Bool] = []
    var artistNames     :[String] = []
    var musicNames      :[String] = []
    var urlImageArtista :[String] = []
    var listaMusic      :[Pergunta] = []
    let perguntas = [
        Pergunta(id           :0,
                 nomeMusica   :"Banho de sol",
                 nomeArtista  :"Baco Exu do Blues",
                 questao      :"Quem é o músico",
                 respostas    :["Djonga",
                                "BK",
                                "Pixinguinha",
                                "Baco Exu do Blues"],
                 correct      :3,
                 musica       :"spotify:track:2SFqE5mNkWXZfAcHSVhKAG"),
        
        Pergunta(id           :1,
                 nomeMusica   :"You don't know me",
                 nomeArtista  :"Caetano Veloso",
                 questao      :"Quem é o músico",
                 respostas    :["Caetano Veloso",
                                "Elton John",
                                "Paul McCartney",
                                "Chico Buarque"],
                 correct      :0,
                 musica       :"spotify:track:7Fw7VPZTX461fLYo72UkV1"),
        
        Pergunta(id           :2,
                 nomeMusica   :"Steve Lacy",
                 nomeArtista  :"Dark Red",
                 questao      :"Quem é o músico",
                 respostas    :["Tuyo",
                                "Steve Lacy",
                                "Tyler, The Creator",
                                "Rex Orange County"],
                 correct      :1,
                 musica       :"spotify:track:37y7iDayfwm3WXn5BiAoRk"),
        
        Pergunta(id           :3,
                 nomeMusica   :"Carinhoso",
                 nomeArtista  :"Pixinguinha",
                 questao      :"Quem é o músico",
                 respostas    :["Vinicius de Morais",
                                 "Pixinguinha",
                                 "Baden Powell",
                                 "Alvin e os Esquilos"],
                 correct      :1,
                 musica       :"spotify:track:0Z9kYW51a2Fh8YHN0NtGQn"),
        
        Pergunta(id           :4,
                 nomeMusica   :"Phonyppl",
                 nomeArtista  :"Somehow.",
                 questao      :"Qual é o nome\nda música",
                 respostas    :["Somehow.",
                                "DARKRYD",
                                "Loving you",
                                "Sunflower"],
                 correct      :0,
                 musica       :"spotify:track:2zk7TQx9Xa4yxYmsjgDCPp"),
        
        Pergunta(id           :5,
                 nomeMusica   :"Rex Orange County",
                 nomeArtista  :"Sunflower",
                 questao      :"Qual é o nome\nda música",
                 respostas    :["Roses",
                                "ForeWord",
                                "Sunflower",
                                "Haruka Kanata"],
                 correct      :2,
                 musica       :"spotify:album:1FhmTMNe8AziAPkB29114F"),
        
        Pergunta(id           :6,
                 nomeMusica   :"Lianne La havas",
                 nomeArtista  :"Au cinema",
                 questao      :"Qual o nome\nda cantora",
                 respostas    :["Lianne La Havas",
                                "Esperanza Spalding",
                                "Sia",
                                "Beyoncé"],
                 correct      :0,
                 musica       :"spotify:track:4RYhqQjBtsfqahsqgVcrOq"),
        
        Pergunta(id           : 7,
                 nomeMusica   :"The Lung",
                 nomeArtista  :"Hiatus Kaiyote",
                 questao      :"Qual o nome\nda Banda",
                 respostas    :["Hiatus Kaiyote",
                                "ThunderCat",
                                "The Internet",
                                "Mongolian Chop Squad"],
                 correct      :0,
                 musica       :"spotify:track:45GTuMUP3lNuZcw7MGKfhx"),
        
        Pergunta(id           :8,
                 nomeMusica   :"Ponta de Areia",
                 nomeArtista  :"Esperanza Spalding",
                 questao      :"Quem canta",
                 respostas    :["Maria Rita",
                                "Céu",
                                "Esperanza Spalding",
                                "Bibi Caetano"],
                 correct      :2,
                 musica       :"spotify:album:7188JsHTl3rladofF7CVvW"),
        
        Pergunta(id           :9,
                 nomeMusica   :"Distractions",
                 nomeArtista  :"Sia and Zero 7",
                 questao      :"Quem canta",
                 respostas    :["Beyoncé",
                                "Bibi Caetano",
                                "Madonna",
                                "SIA"],
                 correct      :3,
                 musica       :"spotify:track:6W7SsXRozQ8qEBffSmwycJ"),
        Pergunta(id           :10,
                 nomeMusica   :"Nada / Tudo",
                 nomeArtista  :"O Terno",
                 questao      :"Quem canta",
                 respostas    :["Tagore",
                                "Boogarins",
                                "O Terno",
                                "Marcelo Camello"],
                 correct      :2,
                 musica       :"spotify:track:0qtYehIhoNRaVIryLnbp7O"),
        
        Pergunta(id           :11,
                 nomeMusica   :"ForeWord",
                 nomeArtista  :"Tyler, The Creator",
                 questao      :"Quem Canta",
                 respostas    :["Tyler, The Creator",
                                "A$AP Rocky",
                                "The Fallen",
                                "Los Gringos"],
                 correct      :0,
                 musica       :"spotify:track:33i3xxHB4YSYGYbtJrwwO8"),
        
        Pergunta(id           :12,
                 nomeMusica   :"FoiMal",
                 nomeArtista  :"Boogarins",
                 questao      :"Quem Canta",
                 respostas    :["O Terno",
                                "Boogarins",
                                "Tagore",
                                "Emicida"],
                 correct      :1,
                 musica       :"spotify:track:3KvrjlLsE19DIwj87FV3Uw"),
        Pergunta(id           :13,
                 nomeMusica   :"Solamento",
                 nomeArtista  :"Tuyo",
                 questao      :"Quem Canta",
                 respostas    :["Baco Exu do Blues",
                                "Tuyo",
                                "Mallu Magalhães",
                                "Ginga"],
                 correct      :1,
                 musica       :"spotify:track:5dtVGvYTO7r9wPtmse04Hl"),
        Pergunta(id           :14,
                 nomeMusica   :"Não",
                 nomeArtista  :"Tim Bernades",
                 questao      :"Qual é o nome\nda música",
                 respostas    :["Pra mim",
                                "Não",
                                "Nós Sabemos",
                                "Sim"],
                 correct      :1,
                 musica       :"spotify:track:7EaxLW81WCgYuHSu6UBcMa"),
        
        Pergunta(id           :15,
                 nomeMusica   :"Bixinho",
                 nomeArtista  :"Duda Beat",
                 questao      :"Quem canta",
                 respostas    :["Duda Beat",
                                "Mainha Old School",
                                "Baiana System",
                                "Tigrinha"],
                 correct      :0,
                 musica       :"spotify:track:388J1r4kupLJSr0gxlETie"),
        Pergunta(id           :16,
                 nomeMusica   :"Construçãp",
                 nomeArtista  :"Chico Buarque de Hollanda",
                 questao      :"Quem canta",
                 respostas    :["Djavan",
                                "Chico Buarque",
                                "Franscisco, El hombre",
                                "Emicida"],
                 correct      :1,
                 musica       :"spotify:track:3FIuBxOxuQ6kYy8JO0gq2a"),
        Pergunta(id           :17,
                 nomeMusica   :"",
                 nomeArtista  :"",
                 questao      :"quem canta",
                 respostas    :["Elis Regina",
                                "Miriam Cardoso",
                                "Tom zé",
                                "Belchior"],
                 correct      :3,
                 musica       :"spotify:track:0BoCuzEjDEcULyknBHf3Ii"),
        Pergunta(id           :18,
                 nomeMusica   :"mistério do Planeta",
                 nomeArtista  :"novos Baianos",
                 questao      :"Quem Canta",
                 respostas    :["Chico Buarque",
                                "Novos Baianos",
                                "Duda Beat",
                                "Baiana System"],
                 correct      :1,
                 musica       :"spotify:track:3TAMiM8XFmU9vFd333pgRh"),
        Pergunta(id           :19,
                 nomeMusica   :"",
                 nomeArtista  :"",
                 questao      :"Quem Canta",
                 respostas    :["Mulheres Negras",
                                "14 Bis",
                                "Chico César",
                                "Milton Nascimento"],
                 correct      :3,
                 musica       :"spotify:track:64ZTy1DsCuYufxaBBUSFxA"),
        Pergunta(id           :20,
                 nomeMusica   :"",
                 nomeArtista  :"",
                 questao      :"Qual é o nome\nda música",
                 respostas    :["Desapego",
                                "Boate Azul",
                                "Trem das Onze",
                                "Evidências"],
                 correct      :2,
                 musica       :"spotify:track:7p61tIz7qwzuc9c2WgQjDv"),
        Pergunta(id           :21,
                 nomeMusica   :"",
                 nomeArtista  :"",
                 questao      :"quem canta",
                 respostas    :["Novos Baianos",
                                "Chico Martelo",
                                "Jorge Ben Jor",
                                "Tim Maia"],
                 correct      :2,
                 musica       :"spotify:track:418er4nP9ZkcjB8oNzTEgb"),
        Pergunta(id           :22,
                 nomeMusica   :"",
                 nomeArtista  :"",
                 questao      :"Quem Canta",
                 respostas    :["Emicida",
                                "Criolo",
                                "Black Alien",
                                "Djonga"],
                 correct      :1,
                 musica       :"spotify:track:7e1OrZHVcoXkP4hxLjP3oA")
    ]
}
